### ISSUE TITLE
Better Debugging

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-ui#149]
As a visualization author, I want to have _excellent_ debugging support in VizHub, so that I can debug my code.

This is one of the main reasons for wanting to eject from VizHub.

This can be broken into separate types of debugging, and closed when all of these subtasks are done:

 * [x] Display Rollup Errors #120
 * [x] Display Runtime Errors #150
 * [X] Point to Correct Line Numbers in Errors #151
 

Please :+1: this issue to help prioritize this task in our [backlog](https://github.com/datavis-tech/vizhub-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by curran** [comment]
Done.
