### ISSUE TITLE
[Epic] Working Alpha IDE

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-ui#2]
* [ ] IDE - Code Editor Panel
 * [ ] IDE - File List Panel
 * [ ] IDE - Visuaization Runner
 * [ ] IDE - Run on Shift+Enter
